# Generated by Django 3.2.16 on 2023-03-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='packaging_type',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
