# Generated by Django 3.2.16 on 2023-03-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0003_shipment_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=100),
        ),
    ]
