# Generated by Django 3.2.16 on 2023-03-29 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0004_alter_payment_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swiftdrop.payment'),
        ),
    ]
