# Generated by Django 3.2.16 on 2023-03-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0005_shipment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
