# Generated by Django 3.2.16 on 2023-03-30 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0007_auto_20230330_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swiftdrop.location'),
        ),
    ]
