# Generated by Django 3.2.16 on 2023-03-31 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0008_shipment_delivery_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField(default=False)),
                ('country', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(default=False, max_length=100)),
                ('open_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_time', models.DateTimeField(default=datetime.datetime(2023, 3, 31, 13, 23, 22, 577767, tzinfo=utc))),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_contact', models.CharField(max_length=255)),
            ],
        ),
    ]
