# Generated by Django 3.2.16 on 2023-03-31 08:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0010_alter_stations_close_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_location',
        ),
        migrations.AddField(
            model_name='shipment',
            name='drop_off_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swiftdrop.stations'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 13, 43, 3, 633919, tzinfo=utc)),
        ),
    ]
