# Generated by Django 3.2.16 on 2023-03-31 09:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0012_auto_20230331_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='drop_off_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_shipments', to='swiftdrop.stations'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pick_up_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_up_shipments', to='swiftdrop.stations'),
        ),
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 14, 0, 41, 823547, tzinfo=utc)),
        ),
    ]
