# Generated by Django 3.2.16 on 2023-03-31 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0014_auto_20230331_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 14, 26, 54, 80375, tzinfo=utc)),
        ),
    ]
