# Generated by Django 3.2.16 on 2023-03-31 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0017_auto_20230331_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='distance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 14, 50, 6, 877264, tzinfo=utc)),
        ),
    ]
