# Generated by Django 3.2.16 on 2023-03-31 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0019_auto_20230331_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.AddField(
            model_name='shipment',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 15, 39, 46, 204142, tzinfo=utc)),
        ),
    ]
