# Generated by Django 3.2.16 on 2023-03-31 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0020_auto_20230331_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 31, 15, 47, 42, 161276, tzinfo=utc)),
        ),
    ]
