# Generated by Django 3.2.16 on 2023-04-02 06:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0022_auto_20230401_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 11, 46, 8, 92793, tzinfo=utc)),
        ),
    ]
