# Generated by Django 3.2.16 on 2023-04-04 06:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0024_alter_stations_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 4, 11, 6, 52, 786880, tzinfo=utc)),
        ),
    ]
