# Generated by Django 3.2.16 on 2023-04-06 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiftdrop', '0029_alter_stations_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='sender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 6, 10, 55, 30, 688638, tzinfo=utc)),
        ),
    ]
